### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mohamadrezamomeni**

### CODE REVIEW

**Comment by TheKhanj** [comment]
hajiii🤣🤣

**Comment by mohamadrezamomeni** [comment]
what is your opinion for this pr?

**Comment by TheKhanj** [comment]
You can fork it and accept your own pr there 😛

**Comment by mohamadrezamomeni** [comment]
don't throw me away

**Comment by TheKhanj** [comment]
I had to do take revenge on all PR's of mine that have not been accepted. Unfortunately the one being revenge of turned out to be you 😛

**Comment by TheKhanj** [comment]
Haji man ino merge mikonam fght chon repoto delete kardi khodam patchesho apply mikonm.

**Pull request closed without merging**
